# Generated by Django 6.0 on 2025-12-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='ubicacion',
            field=models.CharField(choices=[('Chaco', 'Chaco'), ('Corrientes', 'Corrientes'), ('Formosa', 'Formosa'), ('Misiones', 'Misiones')], default='Chaco', max_length=50, verbose_name='Provincia'),
        ),
    ]
